name:                haskellbook
version:             0.1.0.0
homepage:            https://github.com/nicolashery/haskellbook
license:             BSD3
author:              Nicolas Hery
maintainer:          hi@nicolashery.com
copyright:           2018 Nicolas Hery
category:            Web
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - checkers
  - containers
  - parsers
  - QuickCheck
  - random
  - text
  - time
  - transformers
  - trifecta
  - scotty
  - split
  - vector

library:
  source-dirs: src

executables:
  haskellbook:
    source-dirs:
      - src
      - bin
    main: Main.hs

benchmarks:
  haskellbook-benchmarks:
    source-dirs:
      - src
      - benchmark
    main: Main.hs
    dependencies:
      - criterion

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - hspec
      - hspec-checkers
